stages:
  - test
  - rebuild
  - post

test-PO-files:
    stage: test
    script:
    - git submodule sync --recursive
    - git submodule update --init --recursive
    - echo 'checking po files for errors.\nyu can do this before pushing too!'
    - wiki/src/contribute/l10n_tricks/check_po.sh
rebuild-wiki:
    stage: rebuild
    script:
        - ikiwiki --setup ikiwiki.setup --rebuild
        - echo 'changes from weblate to update:'
        - git status
post-rebuild:
    stage: post
    script:
        - echo 'last changes in docs'
        - wiki/src/contribute/l10n_tricks/doc-whatchanged '2 days ago'
        - echo 'language statistics'
        - wiki/src/contribute/l10n_tricks/language_statistics.sh

cache:
    key: "$CI_PROJECT_PATH_SLUG-master"
