stages:
  - test
  - refresh

test-PO-files:
    stage: test
    script:
    - git submodule sync --recursive
    - git submodule update --init --recursive
    - wiki/src/contribute/l10n_tricks/check_po.sh
refresh-wiki:
    stage: refresh
    script:
    - ikiwiki --setup ikiwiki.setup --rebuild
    - git status

cache:
    key: "$CI_PROJECT_PATH_SLUG-master"
