stages:
  - test
  - rebuild

test-PO-files:
    stage: test
    script:
    - git submodule sync --recursive
    - git submodule update --init --recursive
    - echo 'checking po files for errors. You can do this before pushing too!'
    - wiki/src/contribute/l10n_tricks/check_po.sh
lang-stats:
    stage: test
    script:
    - echo 'language statistics'
    - wiki/src/contribute/l10n_tricks/language_statistics.sh
rebuild-wiki:
    stage: rebuild
    script:
        - ikiwiki --setup ikiwiki.setup --rebuild
        - echo 'changes from weblate to update:'
        - git status

cache:
    key: "$CI_PROJECT_PATH_SLUG-master"
