stages:
  - test
  - rebuild

test-PO-files:
    stage: test
    script:
    - git submodule sync --recursive
    - git submodule update --init --recursive
    - echo 'checking po files for errors. You can do this before pushing too!'
    - wiki/src/contribute/l10n_tricks/check_po.sh
lang-stats:
    stage: test
    script:
    - echo 'language statistics'
    - wiki/src/contribute/l10n_tricks/language_statistics.sh
rebuild-wiki:
    stage: rebuild
    script:
         # first we build de wiki
        - ikiwiki --setup ikiwiki.setup --rebuild
         # we check there are no new files, and fail if there are,
         # as that will mean weblate needs update
        - git status  | grep -q 'nothing to commit, working tree clean'

cache:
    key: "$CI_PROJECT_PATH_SLUG-master"
