inherit_from: .rubocop_todo.yml
Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table
Style/AccessModifierDeclarations:
  EnforcedStyle: inline
Style/AsciiComments:
  Enabled: false
Style/ClassAndModuleChildren:
  EnforcedStyle: compact
Style/ClassVars:
  Exclude:
    - 'features/support/helpers/dogtail.rb'
    - 'features/support/helpers/remote_shell.rb'
