inherit_from: .rubocop_todo.yml

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Lint/SuppressedException:
  AllowComments: true

Naming/BlockParameterName:
  AllowedNames:
    - expected_patterns_MiB
    - size_MiB
    - size_in_MiB_of_destination_disk

Style/AccessModifierDeclarations:
  EnforcedStyle: inline

Style/AsciiComments:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/ClassVars:
  Exclude:
    - 'features/support/helpers/dogtail.rb'
    - 'features/support/helpers/remote_shell.rb'

Style/NumericLiterals:
  MinDigits: 6

Style/SymbolArray:
  EnforcedStyle: brackets

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: no_comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/WordArray:
  EnforcedStyle: brackets
