# This file (.rubocop.yml) encodes consciously chosen deviation from Rubocop's
# default configuration. The jury is still out regarding other checks, which are
# disabled or tweaked in .rubocop_todo.yml.

inherit_from: .rubocop_todo.yml

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Lint/SuppressedException:
  AllowComments: true

Naming/BlockParameterName:
  AllowedNames:
    - expected_patterns_MiB
    - size_MiB
    - size_in_MiB_of_destination_disk

Naming/MethodName:
  IgnoredPatterns:
    # Cucumber
    - \A(After|Before)Feature\z
    # Case matters: bit vs. byte
    - _(kB|MiB)\z
    # Stay close to Dogtail's API
    - \A(pressKey|roleName|typeText)\z
    # Stay close to OpenCV's API
    - \AmatchTemplate\z

Naming/MethodParameterName:
  AllowedNames:
    - h
    - to
    - vm
    - w
    - x
    - y

Style/AccessModifierDeclarations:
  EnforcedStyle: inline

Style/AsciiComments:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/ClassVars:
  Exclude:
    - 'features/support/helpers/dogtail.rb'
    - 'features/support/helpers/remote_shell.rb'

Style/FormatString:
  EnforcedStyle: percent

Style/GlobalVars:
  Exclude:
    - 'Rakefile'

Style/GuardClause:
  MinBodyLength: 3

Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys

Style/NumericLiterals:
  MinDigits: 6

Style/SymbolArray:
  EnforcedStyle: brackets

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: no_comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/WordArray:
  EnforcedStyle: brackets
