# This file (.rubocop.yml) encodes consciously chosen deviation from Rubocop's
# default configuration. The jury is still out regarding other checks, which are
# disabled or tweaked in .rubocop_todo.yml.

inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    # Let's ignore this script until we start using it and maintaining
    # the corresponding doc-source-relationships.yml
    - 'bin/doc-impacted-by'
  # XXX:Buster: bump to 2.5 once we require Buster to build Tails and to run our
  # test suite
  TargetRubyVersion: 2.3

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Lint/SuppressedException:
  AllowComments: true

Metrics/AbcSize:
  Max: 30

Metrics/BlockLength:
  Max: 27
  ExcludedMethods:
    # Rake
    - 'namespace'
    - 'task'
    # Vagrant
    - 'Vagrant.configure'

Metrics/CyclomaticComplexity:
  Max: 9

Metrics/MethodLength:
  Max: 30

Metrics/ParameterLists:
  CountKeywordArgs: false

Metrics/PerceivedComplexity:
  Max: 10

Naming/BlockParameterName:
  AllowedNames:
    - expected_patterns_MiB
    - size_MiB
    - size_in_MiB_of_destination_disk

Naming/MethodName:
  IgnoredPatterns:
    # Cucumber
    - \A(After|Before)Feature\z
    # Case matters: bit vs. byte
    - _(kB|MiB)\z
    # Stay close to Dogtail's API
    - \A(pressKey|roleName|typeText)\z
    # Stay close to OpenCV's API
    - \AmatchTemplate\z

Naming/MethodParameterName:
  AllowedNames:
    - h
    - to
    - vm
    - w
    - x
    - y

Style/AccessModifierDeclarations:
  EnforcedStyle: inline

Style/AsciiComments:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/ClassVars:
  Exclude:
    - 'features/support/helpers/dogtail.rb'
    - 'features/support/helpers/remote_shell.rb'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GlobalVars:
  Exclude:
    - 'Rakefile'

Style/GuardClause:
  MinBodyLength: 3

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys

Style/NumericLiterals:
  MinDigits: 6

Style/SymbolArray:
  EnforcedStyle: brackets

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: no_comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/WordArray:
  EnforcedStyle: brackets
