inherit_from: ../.rubocop.yml

Layout/LineLength:
  Description: The first line of step definitions can be very long.
  Max: 283

Lint/AmbiguousRegexpLiteral:
  Description: This makes defining steps less verbose.
  Enabled: false
