inherit_from: ../.rubocop.yml

Naming/VariableName:
  EnforcedStyle: snake_case
  Enabled: false

Style/GlobalVars:
  Description: Our test suite relies heavily on this design pattern.
  Enabled: false
