---
- match-exe-paths:
    - '/usr/bin/onionshare'
    - '/usr/bin/onionshare-gui'
  match-users:
    - 'amnesia'
  commands:
    GETINFO:
      - 'version'
      - 'onions/current'
    GETCONF:
      - '__owningcontrollerprocess'
    ADD_ONION:
      - 'NEW:BEST Port=80,176([0-4][0-]|50)'
    DEL_ONION:
      - '.+'
  events:
    SIGNAL:
      suppress: true
    CONF_CHANGED:
      suppress: true
    HS_DESC:
