---
- cmdline:
    - '/usr/bin/python3 /usr/bin/onionshare'
    - '/usr/bin/python3 /usr/bin/onionshare-gui'
  commands:
    GETINFO:
      - 'version'
      - 'onions/current'
    GETCONF:
      - '__owningcontrollerprocess'
    ADD_ONION:
      - 'NEW:BEST Port=80,176\d\d'
    DEL_ONION:
      - '.+'
  events:
    - 'HS_DESC'
    - 'SIGNAL'
    - 'CONF_CHANGED'
