---
- cmdline:
    - '/usr/bin/python3 /usr/bin/onioncircuits'
  commands:
    GETINFO:
      - 'version'
      - 'circuit-status'
      - 'stream-status'
      - 'ns/id/[a-fA-F0-9]+'
      - 'ip-to-country/\d+\.\d+\.\d+\.\d+'
    GETCONF:
      - 'usemicrodescriptors'
      - '__owningcontrollerprocess'
