---
- cmdline:
    - '/usr/local/lib/tor-browser/firefox -allow-remote --class Tor Browser'
  commands:
    SIGNAL:
      - 'NEWNYM'
    GETCONF:
      - 'bridge'
    GETINFO:
      - 'circuit-status'
      - 'ns/id/[a-fA-F0-9]+'
      - 'ip-to-country/\d+\.\d+\.\d+\.\d+'
  events:
    - 'STREAM'
