---
- match-exe-paths:
    - '/usr/local/lib/tor-browser/firefox-unconfined'
  match-users:
    - 'tor-launcher'
  commands:
    SAVECONF:
      - ''
    GETINFO:
      - 'status/bootstrap-phase'
    GETCONF:
      - 'UseBridges'
      - 'Bridge'
      - 'Socks(4|5)Proxy'
      - 'HTTPSProxy'
    SETCONF:
      - 'UseBridges(=.*)?'
      - 'Bridge(=.*)?'
      - 'Socks(4|5)Proxy(=.*)?'
      - 'Socks5Proxy(Username|Password)(=.*)?'
      - 'HTTPSProxy(Authenticator)?(=.*)?'
      - 'ReachableAddresses(=.*)?'
      - 'DisableNetwork=0'
  events:
    - 'STATUS_CLIENT'
    - 'NOTICE'
    - 'WARN'
    - 'ERR'
