---
- match-exe-paths:
    - '/usr/local/lib/tor-browser/firefox-unconfined'
  match-users:
    - 'tor-launcher'
  commands:
    SAVECONF:
      - ''
    GETINFO:
      - 'status/bootstrap-phase'
  confs:
    UseBridges: ['', '.*']
    Bridge: ['', '.*']
    Socks4Proxy: ['', '.*']
    Socks5Proxy: ['', '.*']
    HTTPSProxy: ['', '.*']
    Socks5ProxyUsername: ['', '.*']
    Socks5ProxyPassword: ['', '.*']
    HTTPSProxyAuthenticator: ['', '.*']
    ReachableAddresses: ['', '.*']
    DisableNetwork: ['0']
  events:
    STATUS_CLIENT:
    NOTICE:
    WARN:
    ERR:
